---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    password: AgB72DXzK7p7xqzmQHVfZWkjhM4NUtPT2RvnSJakJWnjbtRofFg+bPgVMgZTOtrPSIntZyWREPSn3LWOgJo4wNS/d2FqI+fb0cdt6LC2iQOp1g42Cl3zyybLkBTFR+4efybriFFiOggNUhWLo2eDnPhuJBX2Fuoi6yPc/VY5gadGpz78s0Dbpa+ymmUMJluM4FdusD6mIB6pxtJdU1oiC7EU3vIaAeWA5H0mWKM5qTZaX/LNX7FgaOuXZKh7xRSFIdbPKos+Y8GcSvJ75v8p/xFto6MS/YwXZmtbjkak3L8wyYkt17Gc5G2+rJ6k2eN7XRAg2hhqg02MGyIXfYqnd0RFGdNCT/GlXYz6bV8saHZGZKgOF/HvhbBwqPGwrM0DSGv9RLJyk0HyhydzbEn+MHaDiUizCl7xPmwtpjAhLee2K8fb3ejZi2v+vvbIZkl0XxNgcBpadXDq7OLQO0NGOLfgo8wv3H/0VZLNRzLilpcB1TYHsrVXsMPbAqxHMTy5y4xZP80Ka39TjE0Z6wlqdlGlsx5uG4QLVBANJi3jYUxGYoUzRuLWpBF9t7HgFanjkZA/R38Jk1IQePoH0yNoe8Dm4+aM/JPP8RmQNAj0BC8vPqm1InAGjMAMK5/gZRNKCpL3RI6my/M1rQFDH56AA9Vw9pP19K/WlV0RLa69jMao7sBatqPJL+AtwVGgu1Lc99fufG8Ko+hIaZuoTg==
    username: AgCoLGdejBX1viR8dDHGZ6wLcp1OMiqIhNZ0/z3N8wa0oeLd/L2tsh/mpDBAWeVBtMaP7Wp5aYv0FHNB3JjQZDdQKRKjBKAEASiUwVO4aM25uc82f4noxYiJhnyZ4tJrlbCvdyhUZVvNw10yMWIi1glsw+Wa3Z76Oxhp8ZaerfvRZYO2BlwrYkFq0qLrsWtt9/HRsWp1bbytCWRXMEHDoZ1mJCsmuxFQ/eagEvdfnCO/76UHsfDunl6GcXgYiwD9cHmL1cJ/OtAWmsPLeL0FUs6zJdRlkEglaBoAFw4D7AFalFyhZBjBxCkWVlObSYdLAD9z7jdH324DO31QPmhAj7HoSSt/BClGQnxhqvnXAd2BuwjhL16FGheBc9GgFbLHDhirp5HOhar9HKG3mTWhUPRJvjWwKeWdsAATeGw5NgXdbN60pc+TwJiwDROCIltOWbPsdHjC5qpnuDN7zIV5doMTDobNfg6HH9thzIyj534pu3VO5kiiBmphA8b7VVVHk23+MnRMjvhs4FUKO4qsQSpah1/MyR95GIprPBz2II8jzOBG42SGPuitLsY9l1f1o28AF/McQ1UYzCN3ptSu7fc1K/VpqxYTOqc5Kc0QPvoJ/RW/4J8dsFsO2yZQ35s/EmbdlQU0cJBIUe8B/SuY6ptfYpLrQ0Zgboa+TEdbn+AAsYIyZhLnm93PzKR1LJJToJqYPrXxVQ==
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default
    type: Opaque
